[package]
name = "fk_core"
version = "0.1.0"
edition.workspace = true

[dependencies]
bevy_math = { version = "0.15.3", default-features = false }
bevy_input = { version = "0.15.3", default-features = false }
